=== hrs-allbsd/OpenLanguageTools/src/filters/xml_config_parser/resources/xml-config.dtd
<!-- 
 Copyright  2005 Sun Microsystems, Inc.
 All rights reserved Use is subject to license terms.
 
-->



<!-- =================================================================== -->
<!-- DTD:      XML Configuration DTD                                        -->
<!-- PURPOSE:  To define the elements and attributes for the SunTrans 2  -->
<!--           XML file filter.                                          -->
<!-- SYSTEM:   Part of the Open Language Tools XML File Filter            -->
<!-- WRITTEN:  2003/01/27 Brian Kidney, Translation Technology,          -->
<!--           Sun Microsystems Inc.                                     -->
<!-- =================================================================== -->

<!-- =================================================================== -->
<!--                           CHANGE HISTORY                            -->
<!-- Developed by: 2003/01/27 Brian Kidney, Translation Technoloy 
        - First Draft                                                    -->
<!-- =================================================================== -->

<!-- =================================================================== -->
<!--                    ROOT ELEMENT (ROOT = xml-config)                 -->
<!-- =================================================================== -->

<!ELEMENT config (head, body) >

<!-- Represents meta data about the XML file type being configured       -->
<!ELEMENT head ((identifier | namespace), file-type, file-type-description?, author?, generated-by?, generated-date?, last-modified-date?) >

<!-- Indicates how a XML file of this particular type is linked to either a          
     dtd or schema.                                                      -->
<!ELEMENT identifier (dtd | schema)>

<!-- If this XML file type uses a DTD, what is its system or public 
     identifier.                                                         -->
<!ELEMENT dtd (system, public?)>

<!-- The value of the system identifier                                  -->
<!ELEMENT system (#PCDATA)>

<!-- The value of the public identifier                                  -->
<!ELEMENT public (#PCDATA)>

<!-- If this XML file type uses a schema, what is its location.          -->
<!ELEMENT schema (noNamespaceSchemaLocation | schemaLocation)>

<!-- The value of the noNamespaceSchemaLocation attribute.               -->
<!ELEMENT noNamespaceSchemaLocation (#PCDATA)>

<!-- The value of the SchemaLocation attribute.                          -->
<!ELEMENT schemaLocation (#PCDATA)>

<!-- The optional ID of the namesapce of this file                       -->
<!ELEMENT namespace (#PCDATA)>

<!-- The type of XML file (e.g. XHTML, MathML, etc.)                     -->
<!ELEMENT file-type (#PCDATA)>

<!-- A description of the XML file tpye we are dealing with              -->
<!ELEMENT file-type-description (#PCDATA)>

<!-- The person who modified the XML configuration file to make it suitable 
     for use with the XML file type in question.                         -->
<!ELEMENT author (#PCDATA)>

<!-- The tool that auto-generated the XML configuration file.            -->
<!ELEMENT generated-by (#PCDATA)>

<!-- The date on which the XML configuration file was generated.         -->
<!ELEMENT generated-date (#PCDATA)>

<!-- The last date on which the XML configuration file was generated.    -->
<!ELEMENT last-modified-date (#PCDATA)>

<!-- The body of the XML configuration file contains the actual details   
     about the XML file being configured for.                            -->
<!ELEMENT body (config-element*, config-attribute*)>

<!-- A XML elememt of XML file being configured for.                     -->
<!ELEMENT config-element (#PCDATA)>
<!ATTLIST config-element
    root-element        (yes|no)   "no"
    default             (yes|no)   "yes"
    parent              CDATA      #IMPLIED
    translatable        (yes|no)   "yes"
    nonsegmentable      (yes|no)   "no"
    nonsegmentablenowordcount (yes|no)   "no"
    empty               (yes|no)   "no"
    preserve-whitespace (yes|no)   "no"
    hardness      (inline|softflow|soft|hard|hardsubsection|hardsection)  "inline">

<!-- A XML attribute of XML file being configured for.                   -->    
<!ELEMENT config-attribute (#PCDATA)>
<!ATTLIST config-attribute
    default               (yes|no)   "yes"
    parent-element        CDATA      #IMPLIED
    translatable          (yes|no)   "no">

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/scrollkeeper-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<identifier>
<dtd>
<system>http://scrollkeeper.sourceforge.net/dtds/scrollkeeper-omf-1.0/scrollkeeper-omf.dtd</system>
<public>-//OMF//DTD Scrollkeeper OMF Variant V1.0//EN</public>
</dtd>
</identifier>
<file-type>ScrollKeeper OMF</file-type>
<file-type-description>ScrollKeeper Open Source Metadata Framework</file-type-description>
<author>Tim Foster</author>
<generated-by>Tim Foster</generated-by>
<generated-date>11th August 2004</generated-date>
<last-modified-date>11th August 2004</last-modified-date>
</head>

<body>
<config-element translatable="yes" hardness="hard">arevision</config-element>
<config-element translatable="yes" hardness="hard">creator</config-element>
<config-element translatable="yes" hardness="hard">maintainer</config-element>
<config-element translatable="yes" hardness="hard">contributor</config-element>
<config-element translatable="yes" hardness="hard">title</config-element>
<config-element translatable="yes" hardness="hard">date</config-element>
<config-element translatable="yes" hardness="hard">version</config-element>
<!-- not including subject here since it's empty
 <config-element translatable="yes" hardness="hard">subject</config-element>
-->

<config-element translatable="yes" hardness="hard">description</config-element>
<config-element translatable="yes" hardness="hard">type</config-element>
<!-- 
Also not including the following, since they're empty
<config-element translatable="yes" hardness="hard">format</config-element>
<config-element translatable="yes" hardness="hard">identifier</config-element>
<config-element translatable="yes" hardness="hard">language</config-element>
<config-element translatable="yes" hardness="hard">coverage</config-element>
<config-element translatable="yes" hardness="hard">relation</config-element>
<config-element translatable="yes" hardness="hard">rights</config-element>

-->
<config-element translatable="yes" hardness="hard">source</config-element>
</body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/mozilla-rdf-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<namespace>http://www.w3.org/1999/02/22-rdf-syntax-ns#</namespace>
<file-type>W3C RDF documents, as used by Mozilla</file-type>
<file-type-description>This is a test xml config file for these types of document</file-type-description>
<author>Tim Foster</author>
<generated-by>Manually written xml config file</generated-by>
<generated-date>06/Apr/2005</generated-date>
<last-modified-date>06/Apr/2005</last-modified-date>
</head>
<body>
<config-element translatable="yes" hardness="hard">Description</config-element>
</body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/javahelp-index-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<identifier>
<dtd>
<system>index_1_0.dtd</system>
<public>-//Sun Microsystems Inc.//DTD JavaHelp Index Version 1.0//EN</public>
</dtd>
</identifier>
<file-type>JavaHelp Index</file-type>
<file-type-description>JavaHelp Index file</file-type-description>
<author>Tim Foster</author>
<generated-by>Tim Foster</generated-by>
<generated-date>1st June 2005</generated-date>
<last-modified-date>1st June 2005</last-modified-date>
</head>

<body>
<config-element translatable="yes" hardness="hard">indexitem</config-element>
<config-attribute translatable="yes" parent-element="indexitem">text</config-attribute>
</body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/javahelp-toc-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<identifier>
<dtd>
<system>toc_1_0.dtd</system>
<public>-//Sun Microsystems Inc.//DTD JavaHelp TOC Version 1.0//EN</public>
</dtd>
</identifier>
<file-type>JavaHelp TOC</file-type>
<file-type-description>JavaHelp TOC</file-type-description>
<author>Tim Foster</author>
<generated-by>Tim Foster</generated-by>
<generated-date>1st June 2005</generated-date>
<last-modified-date>1st June 2005</last-modified-date>
</head>

<body>
<config-element translatable="yes" hardness="hard">tocitem</config-element>
<config-attribute translatable="yes" parent-element="tocitem">text</config-attribute>
</body>
</config>
