=== hrs-allbsd/OpenLanguageTools/src/filters/xml_config_parser/resources/xml-config.dtd
<!-- 
 Copyright  2005 Sun Microsystems, Inc.
 All rights reserved Use is subject to license terms.
 
-->



<!-- =================================================================== -->
<!-- DTD:      XML Configuration DTD                                        -->
<!-- PURPOSE:  To define the elements and attributes for the SunTrans 2  -->
<!--           XML file filter.                                          -->
<!-- SYSTEM:   Part of the Open Language Tools XML File Filter            -->
<!-- WRITTEN:  2003/01/27 Brian Kidney, Translation Technology,          -->
<!--           Sun Microsystems Inc.                                     -->
<!-- =================================================================== -->

<!-- =================================================================== -->
<!--                           CHANGE HISTORY                            -->
<!-- Developed by: 2003/01/27 Brian Kidney, Translation Technoloy 
        - First Draft                                                    -->
<!-- =================================================================== -->

<!-- =================================================================== -->
<!--                    ROOT ELEMENT (ROOT = xml-config)                 -->
<!-- =================================================================== -->

<!ELEMENT config (head, body) >

<!-- Represents meta data about the XML file type being configured       -->
<!ELEMENT head ((identifier | namespace), file-type, file-type-description?, author?, generated-by?, generated-date?, last-modified-date?) >

<!-- Indicates how a XML file of this particular type is linked to either a          
     dtd or schema.                                                      -->
<!ELEMENT identifier (dtd | schema)>

<!-- If this XML file type uses a DTD, what is its system or public 
     identifier.                                                         -->
<!ELEMENT dtd (system, public?)>

<!-- The value of the system identifier                                  -->
<!ELEMENT system (#PCDATA)>

<!-- The value of the public identifier                                  -->
<!ELEMENT public (#PCDATA)>

<!-- If this XML file type uses a schema, what is its location.          -->
<!ELEMENT schema (noNamespaceSchemaLocation | schemaLocation)>

<!-- The value of the noNamespaceSchemaLocation attribute.               -->
<!ELEMENT noNamespaceSchemaLocation (#PCDATA)>

<!-- The value of the SchemaLocation attribute.                          -->
<!ELEMENT schemaLocation (#PCDATA)>

<!-- The optional ID of the namesapce of this file                       -->
<!ELEMENT namespace (#PCDATA)>

<!-- The type of XML file (e.g. XHTML, MathML, etc.)                     -->
<!ELEMENT file-type (#PCDATA)>

<!-- A description of the XML file tpye we are dealing with              -->
<!ELEMENT file-type-description (#PCDATA)>

<!-- The person who modified the XML configuration file to make it suitable 
     for use with the XML file type in question.                         -->
<!ELEMENT author (#PCDATA)>

<!-- The tool that auto-generated the XML configuration file.            -->
<!ELEMENT generated-by (#PCDATA)>

<!-- The date on which the XML configuration file was generated.         -->
<!ELEMENT generated-date (#PCDATA)>

<!-- The last date on which the XML configuration file was generated.    -->
<!ELEMENT last-modified-date (#PCDATA)>

<!-- The body of the XML configuration file contains the actual details   
     about the XML file being configured for.                            -->
<!ELEMENT body (config-element*, config-attribute*)>

<!-- A XML elememt of XML file being configured for.                     -->
<!ELEMENT config-element (#PCDATA)>
<!ATTLIST config-element
    root-element        (yes|no)   "no"
    default             (yes|no)   "yes"
    parent              CDATA      #IMPLIED
    translatable        (yes|no)   "yes"
    nonsegmentable      (yes|no)   "no"
    nonsegmentablenowordcount (yes|no)   "no"
    empty               (yes|no)   "no"
    preserve-whitespace (yes|no)   "no"
    hardness      (inline|softflow|soft|hard|hardsubsection|hardsection)  "inline">

<!-- A XML attribute of XML file being configured for.                   -->    
<!ELEMENT config-attribute (#PCDATA)>
<!ATTLIST config-attribute
    default               (yes|no)   "yes"
    parent-element        CDATA      #IMPLIED
    translatable          (yes|no)   "no">

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/odf-text-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<namespace>urn:oasis:names:tc:opendocument:xmlns:text:1.0</namespace>
<file-type>Open Document Format text documents namespace</file-type>
<file-type-description>This is a test xml config file for these types of document</file-type-description>
<author>Tim Foster</author>
<generated-by>Manually written xml config file</generated-by>
<generated-date>29/Jun/2005</generated-date>
<last-modified-date>29/Jun/2005</last-modified-date>
</head>
<body>
<config-element translatable="yes" hardness="hard">p</config-element>
<config-element translatable="yes" hardness="inline">s</config-element>
<config-element translatable="yes" hardness="inline">span</config-element>
</body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/transit-ttf-to-xml-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : transit-frame-to-xml.xml
    Created on : June 16, 2004, 4:20 PM
    Author     : timf
    Description:
        Purpose of the document follows.
-->

<!DOCTYPE config SYSTEM '/home/timf/xml-config.dtd'>
<config>
 <head>
    <identifier><dtd><system>transit-something-to-xml-converter.dtd</system>
    </dtd></identifier>
    <file-type>Transit TTF xml files</file-type>
    <file-type-description>These are XML files generated by transit</file-type-description>
    <author>Tim Foster</author>
    <generated-by>Tim Foster - would be nice to have a machine do this in the future though</generated-by>
    <generated-date>Wednesday, June 16th</generated-date>
    <last-modified-date>Friday, January 21st</last-modified-date>
 </head>
 <body>
    <config-element translatable="yes" hardness="hard">p</config-element>
    <config-element translatable="yes" hardness="inline">b</config-element>
    <config-element translatable="yes" hardness="inline">i</config-element>
    <config-element translatable="yes" hardness="inline">XRef</config-element>
    <config-element translatable="yes" hardness="inline">Idx</config-element>
    <config-element translatable="yes" hardness="inline">BmkPoint</config-element>
    <config-element translatable="yes" hardness="inline">Frm</config-element>
    <config-element translatable="yes" hardness="inline">Variable</config-element>
    <config-element translatable="yes" hardness="inline">F</config-element>
 </body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/ooo-text-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<namespace>http://openoffice.org/2000/text</namespace>
<file-type>StarOffice/OpenOffice text documents namespace</file-type>
<file-type-description>This is a test xml config file for these types of document</file-type-description>
<author>Tim Foster</author>
<generated-by>Manually written xml config file</generated-by>
<generated-date>08/Feb/2005</generated-date>
<last-modified-date>08/Feb/2005</last-modified-date>
</head>
<body>
<config-element translatable="yes" hardness="hard">p</config-element>
<config-element translatable="yes" hardness="inline">span</config-element>
</body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/javahelp-map-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<identifier>
<dtd>
<system>map_1_0.dtd</system>
<public>-//Sun Microsystems Inc.//DTD JavaHelp Map Version 1.0//EN</public>
</dtd>
</identifier>
<file-type>JavaHelp Map</file-type>
<file-type-description>JavaHelp Map file</file-type-description>
<author>Tim Foster</author>
<generated-by>Tim Foster</generated-by>
<generated-date>1st June 2005</generated-date>
<last-modified-date>1st June 2005</last-modified-date>
</head>

<body>
<!-- nothing translatable in here -->
</body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/javahelp-helpset-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<identifier>
<dtd>
<system>helpset_1_0.dtd</system>
<public>-//Sun Microsystems Inc.//DTD JavaHelp HelpSet Version 1.0//EN</public>
</dtd>
</identifier>
<file-type>JavaHelp HelpSet</file-type>
<file-type-description>JavaHelp HelpSet</file-type-description>
<author>Tim Foster</author>
<generated-by>Tim Foster</generated-by>
<generated-date>1st June 2005</generated-date>
<last-modified-date>1st June 2005</last-modified-date>
</head>

<body>
<config-element translatable="yes" hardness="hard">name</config-element>
<config-element translatable="yes" hardness="hard">label</config-element>

<config-element translatable="no" nonsegmentablenowordcount="yes" hardness="hard">type</config-element>
<config-element translatable="no" nonsegmentablenowordcount="yes" hardness="hard">data</config-element>
</body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/dcr-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<identifier>
<dtd>
<system>dcr4.5.dtd</system>
</dtd>
</identifier>
<file-type>Java.com DTD</file-type>
<file-type-description>Java.com DTD</file-type-description>
<author>Michael Ryan</author>
<generated-by>M. Ryan</generated-by>
<generated-date>02-06-04</generated-date>
<last-modified-date>02-06-04</last-modified-date>
</head>


<body>
<config-element translatable="yes" hardness="hard">item</config-element>
<config-element translatable="yes" hardness="hard">value</config-element>

<config-attribute translatable="yes" parent-element="item" default="yes">name</config-attribute>
<config-attribute translatable="yes" parent-element="item" default="yes">value</config-attribute>


</body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/netscape-rdf-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<namespace>http://home.netscape.com/NC-rdf#</namespace>
<file-type>Netscape RDF documents, as used by Mozilla</file-type>
<file-type-description>This is a test xml config file for these types of document</file-type-description>
<author>Tim Foster</author>
<generated-by>Manually written xml config file</generated-by>
<generated-date>06/Apr/2005</generated-date>
<last-modified-date>06/Apr/2005</last-modified-date>
</head>
<body>
<config-attribute translatable="yes">name</config-attribute>
<config-attribute translatable="yes">emptysearchtext</config-attribute>
</body>
</config>

=== hrs-allbsd/OpenLanguageTools/src/filters/xml_filter/resources/config-files/javelin-config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "xml-config.dtd">
<config>
<head>
<identifier>
<dtd>
<system>content.dtd</system>
</dtd>
</identifier>
<file-type>Javelin XML</file-type>
<file-type-description>Javelin XML. These files contain block tags with all
PCDATA being translatable (hence this simple config file). There is also content
in CDATA sections, which probably isn't optimal.</file-type-description>
<author>Tim Foster</author>
<generated-by>Tim Foster</generated-by>
<generated-date>17th August 2004</generated-date>
<last-modified-date>17th August 2004</last-modified-date>
</head>
<body>
<!-- No actual additional stuff required, the default behaviour
 is sufficient for these files -->
</body>
</config>
